apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://localhost:5672"
    - name: consumerID
      value: python-app
    - name: durable
      value: false
    - name: deletedWhenUnused
      value: false
    - name: autoAck
      value: false
    - name: deliveryMode
      value: 0
    - name: requeueInFailure
      value: false
    - name: prefetchCount
      value: 0
    - name: reconnectWait
      value: 0
    - name: concurrencyMode
      value: parallel
    - name: publisherConfirm
      value: false
    - name: enableDeadLetter # Optional enable dead Letter or not
      value: true
    - name: maxLen # Optional max message count in a queue
      value: 3000
    - name: maxLenBytes # Optional maximum length in bytes of a queue.
      value: 10485760
    - name: exchangeKind
      value: fanout
